parameters:
  iwin_app.repo.user.class:
    Iwin\Bundle\AppBundle\Entity\UserRepository

services:
  iwin_app.repo.profile:
    class:            %iwin_app.repo.user.class%
    factory_service:  doctrine.orm.entity_manager
    factory_method:   getRepository
    arguments: [IwinAppBundle:User]
