parameters:
  iwin_app.twig.appextension.class:
    Iwin\Bundle\AppBundle\Service\Twig\IwinAppExtension
  iwin_app.listener.controller.class:
    Iwin\Bundle\AppBundle\EventListener\ControllerLoader
  iwin_app.menu.class:
    Iwin\Bundle\AppBundle\Service\Util\MenuBuilder
  iwin_app.uploader.class:
    Iwin\Bundle\AppBundle\EventListener\UploadListener

services:
  # Фабрика меню
  iwin_app.menu:
    class: %iwin_app.menu.class%
  # Главное меню
  iwin_app.menu.main:
    class: Knp\Menu\MenuItem
    factory_service: iwin_app.menu
    factory_method:  createMain
    arguments:
      - @knp_menu.factory
      - @security.context
    tags:
      - { name: knp_menu.menu, alias: iwin.main }
  # Главный контроллер
  iwin_app.listener.controller:
    class: %iwin_app.listener.controller.class%
    arguments:
      - @service_container
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: initController }
  # Twig - основное расширение сайта
  iwin_app.twig.appextension:
    class: %iwin_app.twig.appextension.class%
    public: false
    arguments:
      - params:
          title:    @=parameter('app.title')
          langs:    @=parameter('locales_supported')
          # Является ли текущая локаль стандартной
          localeIsDefault: |
            @=service('service_container').isScopeActive('request') ?
              service('request').getLocale() == parameter('kernel.default_locale') :
              parameter('locale') == parameter('kernel.default_locale')
      - "@=service('service_container').isScopeActive('request') ? service('request') : null"
      - %locales_supported%
    tags:
      - { name: twig.extension }
  iwin_app.uploader:
    class: %iwin_app.uploader.class%
    arguments:
      - @doctrine.orm.entity_manager
      - @oneup_uploader.templating.uploader_helper
      - @iwin_app.image_manager
    tags:
      - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
  iwin_app.image_manager:
    class: Intervention\Image\ImageManager
    arguments:
      - {driver: imagick}