iwin_shared:
  resource: "@IwinSharedBundle/Resources/config/routing.yml"
  prefix: /
  options:
    expose: true

iwin_app:
  resource: "@IwinAppBundle/Resources/config/routing.yml"
  prefix: /
  options:
    expose: true

iwin_advert:
  resource: "@IwinAdvertBundle/Resources/config/routing.yml"
  prefix: /
  options:
    expose: true

iwin_qual:
  resource: "@IwinQualBundle/Resources/config/routing.yml"
  prefix: /
  options:
    expose: true

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
  resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

werkint_framework_extra:
  resource: "@WerkintFrameworkExtraBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

oneup_uploader:
  resource: .
  type: uploader
  options:
    expose: true
