iwin_app:
  resource: "@IwinAppBundle/Resources/config/routing.yml"
  prefix: /
  options:
    expose: true

iwin_advert:
  resource: "@IwinAdvertBundle/Resources/config/routing.yml"
  prefix: /
  options:
    expose: true

iwin_qual:
  resource: "@IwinQualBundle/Resources/config/routing.yml"
  prefix: /
  options:
    expose: true

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
  resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

werkint_framework_extra:
  resource: "@WerkintFrameworkExtraBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oneup_uploader:
  resource: .
  type: uploader
  options:
    expose: true