parameters:
  iwin_shared.file.programmaticfileuploader.class:
    Iwin\Bundle\SharedBundle\Service\File\ProgrammaticFileUploader
  iwin_shared.util.jsmodelprovider.class:
    Iwin\Bundle\SharedBundle\Service\Util\JsmodelProvider

services:
  iwin_shared.file.programmaticfileuploader:
    class: %iwin_shared.file.programmaticfileuploader.class%
    arguments:
      - @iwin_app.file_url_manager


services:
  iwin_shared.util.jsmodelprovider:
    class: %iwin_shared.util.jsmodelprovider.class%
    arguments:
      - %iwin_shared.jsmodeldir%
    tags:
      - { name: werkint.requirejs.jsmodelprovider }
