parameters:
  iwin_shared.file.programmaticfileuploader.class:
    Iwin\Bundle\SharedBundle\Service\File\ProgrammaticFileUploader

services:
  iwin_shared.file.programmaticfileuploader:
    class: %iwin_shared.file.programmaticfileuploader.class%
    arguments:
      - @iwin_app.file_url_manager