<?php

namespace Iwin\Bundle\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FaqMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqMessageRepository extends EntityRepository
{
}
